 global:
   scrape_interval:     15s
   external_labels:
     monitor: 'cardano-node-monitor'

 scrape_configs:
   - job_name: 'ehm-bp' # To scrape data from the cardano node
     scrape_interval: 5s
     static_configs:
       - targets: ['ec2-3-127-229-69.eu-central-1.compute.amazonaws.com:12798']
   - job_name: 'ehm-relay-01' # To scrape data from the cardano node
     scrape_interval: 5s
     static_configs:
       - targets: ['ec2-3-127-229-69.eu-central-1.compute.amazonaws.com:12799']
   - job_name: 'ehm-realy-02' # To scrape data from a node exporter to monitor your linux host metrics.
     scrape_interval: 5s
     static_configs:
       - targets: ['ec2-3-127-229-69.eu-central-1.compute.amazonaws.com:9100']
   - job_name: 'EU1_node_relay' # To scrape data from a node exporter to monitor your linux host metrics.
     scrape_interval: 5s
     static_configs:
       - targets: ['ec2-3-127-229-69.eu-central-1.compute.amazonaws.com:9101']
