 global:
   scrape_interval:     15s
   external_labels:
     monitor: 'cardano-node-monitor'

 scrape_configs:
   - job_name: 'ehm-bp' # To scrape data from the cardano node
     scrape_interval: 5s
     static_configs:
       - targets: ['142.93.79.51:12798']
   - job_name: 'ehm-relay-01' # To scrape data from the cardano node
     scrape_interval: 5s
     static_configs:
       - targets: ['167.71.163.136:12798']
   - job_name: 'ehm-bp' # To scrape data from a node exporter to monitor your linux host metrics.
     scrape_interval: 5s
     static_configs:
       - targets: ['142.93.79.51:9100']
   - job_name: 'ehm-relay-01' # To scrape data from a node exporter to monitor your linux host metrics.
     scrape_interval: 5s
     static_configs:
       - targets: ['167.71.163.136:9100']
#   - job_name: 'EU2_cardano_block' # To scrape data from the cardano node
#     scrape_interval: 5s
#     static_configs:
#       - targets: ['ec2-3-121-201-210.eu-central-1.compute.amazonaws.com:12798']
#   - job_name: 'EU2_cardano_relay' # To scrape data from the cardano node
#     scrape_interval: 5s
#     static_configs:
#       - targets: ['ec2-3-121-201-210.eu-central-1.compute.amazonaws.com:12799']
#   - job_name: 'EU2_node_block' # To scrape data from a node exporter to monitor your linux host metrics.
#     scrape_interval: 5s
#     static_configs:
#       - targets: ['ec2-3-121-201-210.eu-central-1.compute.amazonaws.com:9100']
#   - job_name: 'EU2_node_relay' # To scrape data from a node exporter to monitor your linux host metrics.
#     scrape_interval: 5s
#     static_configs:
#       - targets: ['ec2-3-121-201-210.eu-central-1.compute.amazonaws.com:9101']
